applicationVersion=0.0.1
projectGroup=com.tj.boilerplate


# Project Common Setting Version
kotlinVersion=1.9.22
javaVersion=21
ktlintVersion=12.1.0
openApiVersion=2.1.0
logbackVersion=1.4.7

# Spring dependency versions
springBootVersion=3.2.2
springDependencyManagementVersion=1.1.4
springCloudDependenciesVersion=2023.0.0

# Test
springMockkVersion=4.0.2
